www-client/ungoogled-chromium-bin: remove unused IUSE flags
ERROR: pretend
ERROR: www-client/ungoogled-chromium-bin-109.0.5414.74::pf4public failed (pretend phase):
  USE Flag 'core2' not in IUSE for www-client/ungoogled-chromium-bin-109.0.5414.74

Call stack:
                                    ebuild.sh, line 136:  Called pkg_pretend
  ungoogled-chromium-bin-109.0.5414.74.ebuild, line 127:  Called use 'core2'
                             phase-helpers.sh, line 256:  Called die